name: cinemaAPI
version: 0.0.0.1

dependencies:
- wai == 3.2.3
- wai-extra == 3.1.12.1
- base >= 4.7 && < 5
- scotty == 0.12
- postgresql-simple == 0.6.4
- aeson == 2.1.0.0
- time == 1.9.3
- http-types == 0.12.3

executables:
  cinemaAPI-exe:
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N